version: '3.4'
services:
  graphql:
    build:
      context: ./services/graphql
      dockerfile: build/Dockerfile.dev
    volumes:
      - ./services/graphql:/app
    ports:
      - "80:80"
    environment:
      - GRAPHQL_SERVICE_PORT=80
      - GPRC_SERVICE_PORT=443
      - GPRC_SERVICE_NAME=grpc
    tty: true
  grpc:
    build:
      context: ./services/grpc
      dockerfile: build/Dockerfile.dev
    volumes:
      - ./services/grpc:/app
    ports:
      - "443:443"
    environment:
      - GPRC_SERVICE_PORT=443
    tty: true