version: '3.4'
services:
  graphql:
    build:
      context: ./services/graphql
      dockerfile: build/Dockerfile.dev
    volumes:
      - ./services/graphql:/app
    ports:
      - "80:80"
    tty: true
  grpc:
    build:
      context: ./services/grpc
      dockerfile: build/Dockerfile.dev
    volumes:
      - ./services/grpc:/app
    ports:
      - "81:81"
    tty: true