name: GraphQl service image build and regist
on:
  push:
    branches:
    - master
env:
  GCP_PROJECT: golang-portfolio
  IMAGE: golang-api_sample/graphql
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/graphql
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    - run: |
        gcloud auth configure-docker
    - name: Build
      run: |
        docker build -t gcr.io/$GCP_PROJECT/$IMAGE:$GITHUB_SHA -f build/Dockerfile .
    - name: Push
      run: |
        docker push gcr.io/$GCP_PROJECT/$IMAGE:$GITHUB_SHA